version: "3.7"

x-base: &base
  image: scoperobmosys/bt-implementation:latest
  environment:
    - DISPLAY=${DISPLAY}
    - XDG_RUNTIME_DIR=/run/user/1000
    - XAUTHORITY=/home/scope/.Xauthority
    - YARP_COLORED_OUTPUT=1
    #- YARP_FORWARD_LOG_ENABLE=1
    - YARP_FORWARD_CODEINFO_ENABLE=1
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/home/scope/.Xauthority:rw"
    - "${HOME}/.config/yarp:/home/scope/.config/yarp:rw"
    - "${HOME}/.local/share/yarp:/home/scope/.local/share/yarp:rw"
    - "${XDG_RUNTIME_DIR}/yarp:/run/user/1000/yarp"
    - "/run/user/1000/bus:/run/user/1000/bus"
    - logs-volume:/home/scope/logs
  network_mode: host
  ipc: host
  pid: host
  security_opt:
    - apparmor:unconfined

services:

# Images
  scope:
    image: scoperobmosys/scope:ICRA2021-experiments
    build:
      dockerfile: Dockerfile.scope
      context: .
      args:
        cmake_parallel: 8

  bt-implementation:
    <<: *base
    image: scoperobmosys/bt-implementation:latest
    build:
      dockerfile: Dockerfile.bt-implementation
      context: .
      args:
        cmake_parallel: 8
        username: scope
        uid: 1000
        gid: 1000
    depends_on:
      - scope

# Containers
  yarp-server:
    <<: *base
    container_name: yarp-server
    command: echo "a"

    #gammaray --inject-only --listen tcp://0.0.0.0:40001
  Monitor:
    <<: *base
    container_name: Monitor
    command: sh -c "
      gammaray
        /usr/local/src/bt-implementation/build/bin/monitor"
    depends_on:
      - yarp-server

  IdComponent:
    <<: *base
    container_name: IdComponent
    command: sh -c "
      /usr/local/src/bt-implementation/build/bin/IdComponent"
    depends_on:
      - yarp-server


  GoToComponent:
    <<: *base
    container_name: GoToComponent
    command: sh -c "
      yarp wait /navigation2D_nws_yarp/rpc;
      yarp wait /map2D_nws_yarp/rpc;
      yarp wait /localization2D_nws_yarp/rpc;
      /usr/local/src/bt-implementation/build/bin/GoToComponent"
    depends_on:
      - yarp-server
      # - navigation2DServer
      # - map2DServer
      # - localization2DServer

      #gammaray --inject-only --listen tcp://0.0.0.0:40002
  GoToDestination:
    <<: *base
    container_name: GoToDestination
    command: sh -c "
      cd /usr/local/src/bt-implementation/conf;
      yarp wait /GoToComponent;
      yarp wait /BlackboardComponent;
      gammaray
        /usr/local/src/bt-implementation/build/bin/GoToSkill --from GoToDestination.ini"
    depends_on:
      - yarp-server
      - GoToComponent
      - BlackboardComponent

      #gammaray --inject-only --listen tcp://0.0.0.0:40003
  GoToChargingStation:
    <<: *base
    container_name: GoToChargingStation
    command: sh -c "
      cd /usr/local/src/bt-implementation/conf;
      yarp wait /GoToComponent;
      yarp wait /BlackboardComponent;
      gammaray
        /usr/local/src/bt-implementation/build/bin/GoToSkill --from GoToChargingStation.ini"
    depends_on:
      - yarp-server
      - GoToComponent
      - BlackboardComponent

      #gammaray --inject-only --listen tcp://0.0.0.0:40004
      # WARNING connection randomly fails when injected with gammaray
  IsAtDestination:
    <<: *base
    container_name: IsAtDestination
    command: sh -c "
      cd /usr/local/src/bt-implementation/conf;
      yarp wait /GoToComponent;
        /usr/local/src/bt-implementation/build/bin/IsAtSkill --from IsAtDestination.ini"
    depends_on:
      - yarp-server
      - GoToComponent

      #gammaray --inject-only --listen tcp://0.0.0.0:40005
      # WARNING connection randomly fails when injected with gammaray
  IsAtChargingStation:
    <<: *base
    container_name: IsAtChargingStation
    command: sh -c "
      cd /usr/local/src/bt-implementation/conf;
      yarp wait /GoToComponent;
        /usr/local/src/bt-implementation/build/bin/IsAtSkill --from IsAtChargingStation.ini"
    depends_on:
      - yarp-server
      - GoToComponent

  fakeBattery:
    <<: *base
    container_name: fakeBattery
    command: sh -c "
      yarpdev --device fakeBattery --name /fakeBattery"
    depends_on:
      - yarp-server

  fakeBatteryChargingStation:
    <<: *base
    container_name: fakeBatteryChargingStation
    command: sh -c "
      yarp wait /navigationServer/rpc;
      yarp wait /mapServer/rpc;
      yarp wait /localizationServer/rpc;
      yarp wait /fakeBattery/rpc:i;
      yarp wait /fakeBattery/data:o;
      yarp wait /fakeBattery/control/rpc:i;
      /usr/local/src/bt-implementation/build/bin/fakeBatteryChargingStation"
    depends_on:
      - yarp-server
      # - navigation2DServer
      # - map2DServer
      # - localization2DServer
      - fakeBattery

  yarpbatterygui:
    <<: *base
    container_name: yarpbatterygui
    command: sh -c "
      yarp wait /fakeBattery/rpc:i;
      yarp wait /fakeBattery/data:o;
      yarpbatterygui --remote /fakeBattery --refresh_period 1.0"
    depends_on:
      - yarp-server
      - fakeBattery

  BatteryComponent:
    <<: *base
    container_name: BatteryComponent
    command: sh -c "
      yarp wait /fakeBattery/rpc:i;
      yarp wait /fakeBattery/data:o;
      /usr/local/src/bt-implementation/build/bin/BatteryComponent"
    depends_on:
      - yarp-server
      - fakeBattery

      #gammaray --inject-only --listen tcp://0.0.0.0:40006
  BatteryLevelSkill:
    <<: *base
    container_name: BatteryLevelSkill
    command: sh -c "
      cd /usr/local/src/bt-implementation/conf;
      yarp wait /monitor;
      yarp wait /BatteryComponent;
      gammaray
        /usr/local/src/bt-implementation/build/bin/BatteryLevelSkill --from BatteryLevel.ini"
    depends_on:
      - yarp-server
      - Monitor
      - BatteryComponent

      #gammaray --inject-only --listen tcp://0.0.0.0:40007
  BatteryNotChargingSkill:
    <<: *base
    container_name: BatteryNotChargingSkill
    command: sh -c "
      cd /usr/local/src/bt-implementation/conf;
      yarp wait /BatteryComponent;
      gammaray
        /usr/local/src/bt-implementation/build/bin/BatteryNotChargingSkill --from BatteryNotCharging.ini"
    depends_on:
      - yarp-server
      - BatteryComponent


  BlackboardComponent:
    <<: *base
    container_name: BlackboardComponent
    command: sh -c "
      cd /usr/local/src/bt-implementation/build/bin;
      ./BlackboardComponent"
    depends_on:
      - yarp-server


  BehaviorTree:
    <<: *base
    container_name: BehaviorTree
    command: sh -c "
      cd /usr/local/src/bt-implementation/build/bin;
      yarp wait /monitor;
      yarp wait /GoToDestination/BT_rpc/server;
      yarp wait /GoToChargingStation/BT_rpc/server;
      yarp wait /BatteryLevel/BT_rpc/server;
      yarp wait /BatteryNotCharging/BT_rpc/server;
      yarp wait /IsAtDestination/BT_rpc/server;
      yarp wait /IsAtChargingStation/BT_rpc/server;
      ./from_xml_example"
    depends_on:
      - yarp-server
      - Monitor
      - GoToDestination
      - GoToChargingStation
      - BatteryLevelSkill
      - BatteryNotChargingSkill
      - IsAtDestination
      - IsAtChargingStation

  groot:
    <<: *base
    container_name: groot
    command: Groot --mode monitor
    depends_on:
      - BehaviorTree

volumes:
  logs-volume:
